name: Java CI (Maven)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) checkout your code
      - name: Checkout
        uses: actions/checkout@v4

      # 2) set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # 3) cache Maven dependencies
      - name: Cache Maven local repo
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # 4) build & test
      - name: Build & run tests
        run: mvn --batch-mode clean test

      # 5) package
      - name: Package
        run: mvn --batch-mode package -DskipTests=false

      # 6) upload test reports
      - name: Upload Surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports

      - name: Test report
        if: always()
        uses: dorny/test-reporter@v2
        with:
          name: JUnit Tests
          # since we uploaded your Surefire XMLs under this name:
          artifact: surefire-reports
          # path inside that artifact
          path: '*.xml'
          # pick the JUnit parser
          reporter: java-junit
          # generate only a summary (omit per-test details if you like)
          only-summary: 'false'
          # post it as a GitHub Actions Summary too
          use-actions-summary: 'true'
          badge-title: 'tests'
          # fail the check run if any tests failed
          fail-on-error: 'true'
          # fail if you didn’t even find any reports
          fail-on-empty: 'true'
